AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  loadcsvdominomodelmonitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        <Your Lambda Function Service Role ARN>
      Environment:
        Variables:
          DMM_API_TOKEN: >-
            <Your Domino Model Monitor API Token>
          DMM_URL: 'https://trial.dmm.domino.tech/api/v0/models/'
          PRED_FILE_KEY: <Your S3 Key for the prediction file to be written>
          S3_BUCKET: <Your S3 Bucket Name>
